In [1]:
import numpy as np

In [14]:
x = np.array([[0,0,2],[1,0,0],[0,1,0]])

In [15]:
x

array([[0, 0, 2],
       [1, 0, 0],
       [0, 1, 0]])

In [13]:
np.dot(x,x)

array([[0, 2, 0],
       [0, 0, 2],
       [1, 0, 0]])

In [11]:
np.dot(x,np.dot(x,x))

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

In [19]:
X = np.array([x, np.dot(x,x), np.dot(x, np.dot(x,x))])
X[0]

array([[0, 0, 2],
       [1, 0, 0],
       [0, 1, 0]])

In [27]:
a = np.array([1, 2**0.333333, 4**0.333333])
np.dot(a, np.dot(x,np.dot(x,x))[:,0])

2.0

In [120]:
import numpy as np

w = [1,2**(1.0/3), 4**(1.0/3)]
z = [1,2**(1.0/3), 4**(1.0/3)]
x = np.array([[1,0,0],[0,1,0],[0,0,1]])
y = np.array([[1,0,0],[0,1,0],[0,0,1]])
code = ''

T = 4
for k in range(1+18*T):
    #z = [z[0], z[1], z[2]-z[1]]

    x = np.dot(np.array([[1,0,0],[0,1,1],[0,0,1]]),x)
    y = np.dot(np.array([[1,0,0],[0,1,0],[0,-1,1]]),y)
    z = np.dot(y,w)
    
    if(z[2] > z[1]):
        print "a",
        code += 'a'
        x = np.dot(np.array([[1,0,0],[0,1,0],[0,0,1]]),x)
        y = np.dot(np.array([[1,0,0],[0,1,0],[0,0,1]]),y)        
    if(z[2] < z[1] and z[2] > z[0]):
        print "b",
        code += 'b'
        #z = [z[0], z[2], z[1]]
        x = np.dot(np.array([[1,0,0],[0,0,1],[0,1,0]]),x)
        y = np.dot(np.array([[1,0,0],[0,0,1],[0,1,0]]),y)        
    if(z[2] < z[1] and z[2] < z[0]):
        print "c",
        #z = [z[2], z[0], z[1]]
        code += 'c'
        x = np.dot(np.array([[0,0,1],[1,0,0],[0,1,0]]),x)
        y = np.dot(np.array([[0,0,1],[1,0,0],[0,1,0]]),y)
        
    print np.dot(y,w)
    
for k in range(T):
    print code[1+k*18: 1+(k+1)*18]

z, (code[1:19]== code[19:37]),np.dot(z,x),x, 
#z, (code[1:19]== code[19:37]), code[1:1+18], code[1+18:1+2*18], code[1+2*18:1+3*18], np.dot(x,z)

c [ 0.32748     1.          1.25992105]
c [ 0.25992105  0.32748     1.        ]
a [ 0.25992105  0.32748     0.67252   ]
a [ 0.25992105  0.32748     0.34504   ]
c [ 0.01755999  0.25992105  0.32748   ]
b [ 0.01755999  0.06755895  0.25992105]
a [ 0.01755999  0.06755895  0.1923621 ]
a [ 0.01755999  0.06755895  0.12480315]
b [ 0.01755999  0.05724419  0.06755895]
c [ 0.01031476  0.01755999  0.05724419]
a [ 0.01031476  0.01755999  0.0396842 ]
a [ 0.01031476  0.01755999  0.02212421]
c [ 0.00456421  0.01031476  0.01755999]
b [ 0.00456421  0.00724523  0.01031476]
c [ 0.00306952  0.00456421  0.00724523]
c [ 0.00268102  0.00306952  0.00456421]
c [ 0.00149469  0.00268102  0.00306952]
c [ 0.0003885   0.00149469  0.00268102]
b [ 0.0003885   0.00118633  0.00149469]
c [ 0.00030835  0.0003885   0.00118633]
a [ 0.00030835  0.0003885   0.00079783]
a [ 0.00030835  0.0003885   0.00040933]
c [  2.08320314e-05   3.08353382e-04   3.88500916e-04]
b [  2.08320314e-05   8.01475347e-05   3.08353382e-04]
a [  2.083

(array([ -2.91038305e-11,   0.00000000e+00,   0.00000000e+00]),
 True,
 array([-1.34130009, -1.68993222, -2.12918117]),
 array([[ 46086720140,  58065628825,  73158108032],
        [210040534251, 264634490434, 333418565026],
        [191509072163, 241286311264, 304001702613]]))

In [82]:
xinv = np.round(np.linalg.inv(x)).astype(int)
xinv

array([[-1079,   434,  -347],
       [  583, -1079,  2096],
       [  217,   583, -1445]])

In [83]:
np.dot(x, xinv)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [91]:
y

array([[-1079,  -347,   434],
       [  217, -1445,   583],
       [  583,  2096, -1079]])

In [93]:
np.dot(y,[1,2**0.33333333333, 4**0.33333333333])

array([ -827.26054776,  -678.1311038 ,  1510.98878551])